feat: add login button components for Web
gdsc-ssu/sasil-front pull request #19
Opened 2022-03-20 16:11 UTC by ballsona

## Issue
https://github.com/gdsc-ssu/sasil-front/issues/13 로그인 컴포넌트 UI 구현

## Description
Web용 로그인 버튼 컴포넌트를 Atom 단위로 구현하였다.
storybook 으로 테스트 가능하도록 story 파일도 함께 생성했다.

## Check List

- [x] PR 제목을 commit 규칙에 맞게 작성
- [x] WIP를 붙여야 하는 상황인지 확인
- [x] label 설정
- [x] 작업한 사람 모두를 Assign
- [x] Code Review 요청

2022-03-21 05:38 UTC, kanghyun98 commented on projects/sasil-web/src/components/common/atom/LoginButton/LoginButton.tsx
> +}
`LoginButtonProps`를 `export`해줘서 storybook에서도 import해서 사용하는 방식은 어때?
중복되는 부분은 최대한 줄이는게 좋을 것 같아서!

2022-03-21 05:38 UTC, kanghyun98 commented on projects/sasil-web/src/components/common/atom/LoginButton/LoginButton.stories.tsx
> +} as ComponentMeta<typeof LoginButton>;
내가 스토리북을 아직 잘 몰라서..
혹시 이 부분이 스토리북을 실행시키기 위해 필요한건가..??

2022-03-21 05:38 UTC, kanghyun98 commented on projects/sasil-web/src/components/common/atom/LoginButton/LoginButton.tsx
> +    color={socialStyle[social].color}
`socialStyle.social.backgroundColor` 방식으로 해주는게 통일성 측면에서 조금 더 정확한 것 같아!
  `socialStyle` 객체의 프로퍼티로 `social` 이라는 또다른 객체가 있는거라 통일성있게 둘 다 `.`로 객체 내부의 값을 불러오는 방식을 이용하는게 좋을듯!
(외부에선 `[]` 방식으로 내부에서는 `.` 방식을 이용해서 값을 가져오는게 조금 어색해유..)

2022-03-22 00:45 UTC, kanghyun98 commented on projects/sasil-web/src/components/common/atom/LoginButton/LoginButton.tsx
> +    color={socialStyle[social].color}
아니면 내가 모르는 무언가가 있는건가..??

2022-03-22 07:54 UTC, aube-dev requested changes

2022-03-22 07:54 UTC, aube-dev commented on projects/sasil-web/src/components/common/atom/LoginButton/LoginButton.tsx
> +interface socialThemesType {
interface는 PascalCase로 하면 좋을 것 같아! 그리고 이건 회의때 한번 다시 정해보면 좋을 것 같은데 그냥 'type'은 안 붙여도 되지 않을까 싶기도 하고...? 그래서 나는 `SocialTheme` 이런 느낌이 가장 좋은 것 같아

2022-03-22 07:54 UTC, aube-dev commented on projects/sasil-web/src/components/common/atom/LoginButton/LoginButton.tsx
> +  [key: string]: {
여기서 key는 `'kakao'`, `'apple'`, `'google'` 중 하나일 텐데, 그럼 이 3개를 타입으로 따로 빼서 관리하는 게 좋을 것 같아!

```typescript
export const SOCIAL = {
  kakao: 'kakao',
  apple: 'apple',
  google: 'google',
} as const;
export type Social = typeof SOCIAL[keyof typeof SOCIAL];

interface SocialTheme {
  [key: Social]: {
    label: string;
    backgroundColor: string;
    color: string;
    logo: ReactElement;
  }
}
```

2022-03-22 07:54 UTC, aube-dev commented on projects/sasil-web/src/components/common/atom/LoginButton/LoginButton.tsx
> +  social: string;
위와 마찬가지로
```suggestion
  social: Social;
```

2022-03-22 07:54 UTC, kanghyun98 commented on projects/sasil-web/src/components/common/atom/LoginButton/LoginButton.tsx
> +    color={socialStyle[social].color}
소나와 얘기해본 결과 social은 변수로 들어가기 때문에 기존 방식이 맞아요..

2022-03-22 07:56 UTC, kanghyun98 commented on projects/sasil-web/src/components/common/atom/LoginButton/LoginButton.tsx
> +    color={socialStyle[social].color}
그러네 기존 방식이 맞다! 다음부턴 집중해서 볼게...

2022-03-22 07:57 UTC, aube-dev commented on projects/sasil-web/src/components/common/atom/LoginButton/LoginButton.tsx
> +    color={socialStyle[social].color}
여기서 `[social]`은 'social'이라는 이름의 property를 참고하는 게 아니라, 컴포넌트의 prop으로 들어온 `social`이라는 변수의 값을 이용해서 해당하는 정보를 찾는 거기 때문에 저게 맞을 것 같아! `.` 방식을 쓴다면 `socialStyle.social`이라는 건 없고, `socialStyle.kakao`, `socialStyle.google`, `socialStyle.apple`로 써야 하니깐

2022-03-22 08:26 UTC, ballsona commented on projects/sasil-web/src/components/common/atom/LoginButton/LoginButton.tsx
> +interface socialThemesType {
`SocialTheme` 나도 얘가 더 좋은 것 같아,, 작명센스를 키워볼게  :)

2022-03-22 08:26 UTC, ballsona commented on projects/sasil-web/src/components/common/atom/LoginButton/LoginButton.tsx
> +  [key: string]: {
이게 타입스크립트구나 를 느낀다.. 반영할게 고마워 !!

2022-04-03 06:02 UTC, ballsona reviewed
- 광서꺼 참고해서 textStyles.ts 를 만들어봤는데, 틀린게 있다면 알려주세요,,
- atom 단위로 StyledText 만들었는데 style 부분을 StyledText.style.tsx로 따로 분리하는게 애매해서 그냥 StyledText.tsx 에 넣었어요
- 일단 web 버튼 컴포넌트만 수정했는데, commit message에다가 (web) 적는걸 깜빡했습니다,,, 죄송함다

2022-04-03 06:12 UTC, ballsona commented on projects/sasil-web/src/components/common/molelcules/LoginButton/LoginButton.tsx
> +    </styles.labelWrap>
Login button 단위?를 molecule로 변경했고, 안에 들어가는 button label은 styledText(atom)으로 바꿔줬어! 
버튼에 들어가는 icon은 atom에서 따로 처리할게 없어서 바로 불러왔는데, 혹시 이게 아니라면 알려주세요,,

2022-04-04 08:35 UTC, aube-dev commented on projects/sasil-web/src/constants/styles/textStyles.ts
> +  bold: 'bold',
웹에서는 font family 이거 쓰면 안 돼! 아마 'Pretendard'일 거야

2022-04-04 14:23 UTC, ballsona commented on projects/sasil-web/src/constants/styles/textStyles.ts
> +  bold: 'bold',
아 그렇군..  수정하겠슴다!!

2022-04-19 07:07 UTC, kanghyun98 approved these changes
🐰  고생했수다.. 코드 전반적으로 깔끔하고 좋으다👍🏼 
아 그리고 리뷰에도 남겨놨는데, atomic design 관련 부분은 회의 때 정리해서 물어볼게!

2022-04-19 07:07 UTC, kanghyun98 commented on projects/sasil-web/src/components/common/atoms/StyledText/StyledText.tsx
> +}));
🐰 `textStyleName`으로 텍스트 타입별로 구분하는거 너무 좋다..!!👍
🥝  이건 진짜 신경 1도 안쓰고 넘어가도 되는 생각인데, `textType` 이라는 변수명도 괜찮을듯?

2022-04-19 07:07 UTC, kanghyun98 commented on projects/sasil-mobile/src/components/common/atom/StyledText/StyledText.tsx
> +}));
웹에서는 `textStyleName`로 텍스트 종류별로 구분했던 것 같은데, 모바일에서는 따로 구분되는게 없나..?

2022-04-19 11:58 UTC, ballsona commented on projects/sasil-mobile/src/assets/icons/AppleLogo.tsx
> +import * as React from 'react';
아 이거 `react-native-svg` 에러 해결하려고 이것저것 뜯어보다가 혹시 해서 바꿔본건데.. 다시 돌려놓는게 맞겠다

2022-04-19 11:59 UTC, ballsona commented on projects/sasil-mobile/src/components/common/molecule/LoginButton/LoginButton.tsx
> +);
일단 `StyledText` 는 `atom` 으로 넣었구, logo 컴포넌트를 asset에 넣을까, atom에 넣을까 고민하다가 일단 의미?상 assets에 넣었는데 회의(1분후)에서 얘기해봅시당

2022-04-20 01:07 UTC, aube-dev requested changes

2022-04-20 01:07 UTC, aube-dev commented on projects/sasil-web/src/constants/styles/textStyles.ts
> +  bold: 'bold',
🍎 이거 처리 부탁해요!! 아마 웹에서는 css에서 global style로 `@font-face`를 정의한 뒤에 `font-family`를 `'Pretendard'`로 통일해야 할 거고, 모바일의 경우 `expo-font`를 이용해서 불러오면 돼

2022-05-01 17:25 UTC, ballsona reviewed
- @sasil/common에 textStyle.ts 지정
일단 `TEXT_STYLE_WEB` 과 `TEXT_STYLE_MOBILE` 로 웹 모바일 따로 나눠서 폰트 스타일을 지정해주었어요.
컴포넌트에서 폰트 지정해줄땐 공통으로 `TEXT_STYLE_NAME.button1R` 처럼 사용가능합니다!
더 나은 방법을 찾지 못해 코드가 길어도 일단 이렇게 만들어봤는데, 나은 방법이 있다면 "사과"든 뭐든지 환영합니다,,, ㅠㅠ
- 웹,모바일 각각 폰트 적용
- @sasil/web, @sasil/mobile 의 폴더 구조를 회의에서 수정했던 atomic design 구조로 변경

2022-05-02 04:27 UTC, aube-dev requested changes
🐰 주석 잘 써줘서 이해가 잘 돼요!!

2022-05-02 04:27 UTC, aube-dev commented on projects/sasil-mobile/src/components/common/molecule/LoginButton/LoginButton.tsx
> +import { TEXT_STYLE_NAME } from '@sasil/common/src/constants/style/textStyles';
🍌이렇게 경로로 불러오는 것보다는, 진짜 npm 모듈을 쓴다고 생각하고 `from '@sasil/common'`으로 불러오는 게 어떨까? `@sasil/common`의 `index.ts`에서 모든 걸 export하는 걸로!

2022-05-02 04:27 UTC, aube-dev commented on projects/sasil-web/src/constants/styles/global.css
> +}
`@font-face` 없어도 잘 돌아가나...? 로컬에 저 폰트가 안 깔려 있을 때 어떻게 나오는지 한번 봐야 할 것 같아!

2022-05-02 14:42 UTC, kanghyun98 reviewed
타입스크립트 지대로 잘 썼구마잉👍🏼👍🏼  주석도 깔꼼하고 👍🏼👍🏼

아 그런데 하나만 부탁할게! `package.json`에 `^`가 몇개 있을텐데 그것좀 지워줍쇼..!

2022-05-02 14:42 UTC, kanghyun98 commented on projects/sasil-web/src/components/molelcules/LoginButton/LoginButton.tsx
> +import StyledText from '../../atoms/StyledText/StyledText';
🥝  절대 경로 써주면 더 좋을듯!
`import StyledText from '@/components/atoms/StyledText/StyledText';`

2022-05-02 14:42 UTC, kanghyun98 commented on projects/sasil-web/src/components/molelcules/LoginButton/LoginButton.tsx
> +);
되게 신기한게 다른데서는 `props`로 그냥 사용하고 여기서는 왜 구조분해할당 썼지? 하고 `props`로 바꿔보니깐 구조분해할당 쓰라고 eslint 오류 뜬다..ㅋㅋㅋ 왜 위에서는 안뜨지..? 신기하네;;

🥝  다른데 구조분해할당 적용하는건 너의 자유에 맡길게..!ㅋㅋ

2022-05-02 14:42 UTC, kanghyun98 commented on projects/sasil-web/src/components/atoms/StyledText/StyledText.stories.tsx
> +// storybook에서 color와 textStyle을 옵션으로 선택해서 테
테...스트?ㅋㅋㅋㅋㅋ

2022-05-03 09:02 UTC, ballsona commented on projects/sasil-mobile/src/assets/icons/AppleLogo.tsx
> +  </Svg>
올렸다 내 첫 Wiki..! 많관부

2022-05-03 09:07 UTC, ballsona commented on projects/sasil-mobile/src/components/common/molecule/LoginButton/LoginButton.tsx
> +import { TEXT_STYLE_NAME } from '@sasil/common/src/constants/style/textStyles';
앗 맞네,, 저번에도 들었는데 자꾸 자동으로 불러오다가 저리 쓴다,, 고맙슴다 !!

2022-05-03 12:35 UTC, aube-dev submitted a review, later dismissed

2022-05-04 14:40 UTC, merged