feat: add social-login logics
gdsc-ssu/sasil-front pull request #22
Opened 2022-05-06 16:14 UTC by ballsona

## Issue
https://github.com/gdsc-ssu/sasil-front/issues/14
## Description
### Web
- Kakao, Apple, Google 로그인 로직 함수를 추가했습니다. 
- `organisms/SocialLoginBox` , `template/AuthTemplate` 구현
- 소셜 로그인 로직 함수를 담은 `template/AuthTemplateWrapped` 추가 -> `AuthTemplate`에 로직 전달
- 로그인 기능을 확인하기 위해 로그인 페이지인 `page/auth` 추가
- 로그인 로직에 쓰이는 id 값 등을 `sasil-common`에 넣은 후 불러오기

## Check List

- [ ] PR 제목을 commit 규칙에 맞게 작성
- [ ] WIP를 붙여야 하는 상황인지 확인
- [ ] label 설정
- [ ] 작업한 사람 모두를 Assign
- [ ] Code Review 요청

2022-05-08 10:45 UTC, aube-dev approved these changes
우선은 LGTM! 바뀐 부분이 너무 많아서 못 본 부분이 꽤 있을 것 같은데, 다행히 여기가 잘못됐다고 다른 기능까지 잘못되는 영역은 아니니까 나중에 다시 보면 좋을 것 같아
다음에는 작업량이 너무 많아진다 싶으면 웹 하나/모바일 하나 이런 식으로 브랜치를 나누어서 작업하면 PR 하나하나 크기를 줄일 수 있을 것 같아요!

2022-05-10 01:32 UTC, kanghyun98 reviewed
🐰  엄청 많은 작업 하느라 고생 많았어!!
그런데 아토믹 구조에 대해서는 약간 얘기해볼 필요가 있을 것 같아오.. (특히 모바일쪽)
이따 회의 때 자세하게 얘기해보자!

2022-05-10 01:32 UTC, kanghyun98 commented on projects/sasil-web/src/components/templates/auth/AuthTemplate/routes.tsx
> +};
🥝  라우터 API는 `common`에서 만들거니깐 여기선 지워줘도 될듯!

2022-05-10 08:29 UTC, ballsona commented on projects/sasil-mobile/App.tsx
> +    semiBold: require('./assets/fonts/Pretendard-SemiBold.otf'),
아냐아냐 이부분 절대경로 쓰니까 자꾸 warning 떠서 바꿨더니 안뜨더라고..? 근데 왜그러는건지 이유는 아직도 모르겠음 ;;..

2022-05-10 08:29 UTC, ballsona commented on projects/sasil-mobile/src/routes/RootNavigator.tsx
> +);
광서 플젝 보고 따라함.... ㅎ

2022-05-10 08:31 UTC, ballsona commented on projects/sasil-web/src/components/templates/auth/AuthTemplate/routes.tsx
> +};
아직 common에 있는 API 쓰기 전상태라, 이 파일을 지우면 컴파일 에러떠서 일단 냅뒀어! 나중에 갈아끼우면(?) 지우께여

2022-05-11 12:26 UTC, kanghyun98 requested changes
🐰  하루만에 수정을 다하다니 멋져..!
사과 하나 있으니 확인해주세요!ㅎ

2022-05-11 12:26 UTC, kanghyun98 commented on projects/common/src/constants/serverInfo.ts
> +export const kakaoRedirectURI = 'https://sasil.app/login';
🍎  만약 로그인 페이지 주소를 `/auth`로 할거면 여기 수정해줘야해! 나는 `/login`으로 생각하고 코드 짰던거여서..
그리고 애플 `redirectURI`도 `https://sasil.app/auth`로 변경해줘야 하고! (기존 값은 테스트 주소고, QA할때 이 부분만 직접 변경해줘서 테스트하는게 맞는것 같아)

아니면 로그인 페이지 주소를 `/login`으로 바꾸는 것도 방법이고,, 두 방법 중 하나 선택해서 알려주세여!
```suggestion
export const kakaoRedirectURI = 'https://sasil.app/auth';
```

2022-05-11 12:26 UTC, kanghyun98 commented on projects/sasil-mobile/src/components/molecule/LoginButton/social/route.ts
> +// axios.defaults.withCredentials = true;
🥝  `axios.defaults.withCredentials = true;` 이 부분은 CORS 요청간에 쿠키 사용하기 위해 추가했던 것인데, 우리 플젝에서는 쿠키를 사용하지 않기로 했으니깐 지워줘도 됩니다! (어차피 주석이라 냅둬도 상관없지만..ㅋㅋㅋ)

2022-05-11 18:26 UTC, kanghyun98 approved these changes
LGTM!
🐰 깔끔해요.. 변경된 아토믹 디자인 반영하느라 고생했슴다!

2022-05-12 13:10 UTC, merged