feat: add post-card components for main-page
gdsc-ssu/sasil-front pull request #28
Opened 2022-05-19 14:59 UTC by ballsona

## Issue
https://github.com/gdsc-ssu/sasil-front/issues/27
## Description

## Check List

- [ ] PR 제목을 commit 규칙에 맞게 작성
- [ ] WIP를 붙여야 하는 상황인지 확인
- [ ] label 설정
- [ ] 작업한 사람 모두를 Assign
- [ ] Code Review 요청

2022-05-21 03:28 UTC, ballsona commented on projects/sasil-web/src/components/molelcules/LoginButton/LoginButton.style.ts
> +}));
로그인 버튼이 Web,Mobile 디자인이 완전 동일한데, 그래서 저번 에픽때 폰트 스타일을 모바일 스타일로 잘못 사용하고 있었더라구여.. 근데 Web용 `textStyle` 에는 {fontSize:14, fontWeight:600} 이 없어서 부득이하게 로그인 버튼만 `TEXT_STYLE_NAME.button` 을 안쓰고 수동으로? 폰트 스타일을 넣어주었어요..
죄송합니다 여러분 앞으로 안그럴게요

2022-05-21 16:43 UTC, kanghyun98 reviewed
🐰  고생 많았고, 코드가 깔끔해서 리뷰하기 편했던 것 같아!

아 그리고 모바일에서는 우리가 `login`으로 변경하기로 했던 부분들이 아직 `auth`로 되어있는게 있더라구! 다음 모바일 작업할 때 참고하면 좋을듯!

2022-05-21 16:43 UTC, kanghyun98 commented on projects/sasil-web/src/components/organisms/post/Post/Post.tsx
> +export const MiniCard = ({
🐰 `MiniCard`라는 변수명 진짜 좋은 것 같다!ㅋㅋㅋ

🍌  여기 파일명도 `Post` -> `MiniCard`로 바꾸면 좋을 것 같아!

🥝  그리고 난 갠적으로 `organism/post`보다는 `organism/main`이 적절해보입니다!

2022-05-21 16:43 UTC, kanghyun98 commented on projects/sasil-web/src/components/molelcules/WriterInfo/WriterInfo.tsx
> + */
🍌  다른 주석들도 마찬가지인데, 여기서 실제로 인자로 받는건 `props` 객체 하나이기 때문에 이게 객체 내부 프로퍼티에 대한 설명이라는 표시가 필요할 것 같아!

아래처럼 주석에 밑줄 그어져있는거를 확인할 수 있음둥!
![image](https://user-images.githubusercontent.com/70627979/169661083-0ddfaba4-9610-4e83-b27b-ecd388c9fcd3.png)

2022-05-21 16:43 UTC, kanghyun98 commented on projects/sasil-web/src/components/molelcules/WriterInfo/WriterInfo.tsx
> + */
아니면 그냥 우리끼리 알아서 진행하는 것도 괜찮고! (이정도는 다 아니깐?ㅋㅋㅋ)

갠적으론 이게 편할듯ㅎ

2022-05-22 13:04 UTC, ballsona commented on projects/sasil-web/src/components/organisms/post/Post/Post.tsx
> +export const MiniCard = ({
지금 우리의 Post 구조가
```
// Post.tsx
export const MiniCard = () => { // 메인 페이지에서 사용될 컴포넌트 } 
export const Card = () => { // 개별 페이지에서 사용될 컴포넌트 }

// page.ts (예시)
import * as Post from '../Post'
<Post.Minicard type="experiment" /> // 메인페이지 실험 게시물 카드
<Post.Card type="experiment" /> // 실험 페이지 게시물 카드
```
요런 느낌이거든. Card 컴포넌트가 따로 분리되서 구현은 되어있는데, `Post.*`로 통일되게 사용되도록 할라고!
그랬더니 발생한 문제가 폴더구조에서 `organisms/[도메인]/Post` 의 도메인을 어떻게 해야할지를 모르겠는건거지..
1. `@/organisms/post/Post` -> 이건 도메인이 아니라 명백히 틀림.. 하하
2. `@/organisms/main/Post` -> 개별 페이지에서 사용되는 `Post.Card` 가 main 내에 있는 셈이 되버린다..
3. 도메인 없이 `@/organisms/Post` ?

2022-05-22 14:35 UTC, ballsona commented on projects/sasil-web/src/components/organisms/post/Post/Post.style.tsx
> +// ? 이때문에 의뢰 게시물은 배경 이미지가 아예 안들어감에도 불구하고 css에는 background 관련 코드가 들어가있는 상황.. 리팩토링 필요
![스크린샷 2022-05-22 23 33 51](https://user-images.githubusercontent.com/67703882/169700580-13bdc9d5-0468-40ba-b56b-fe20696c1556.png)
`<Post.MiniCard type="request" />` 에서 문제가 생기는 부분인데, 의뢰 게시물 카드는 애초에 썸네일이 안들어가서 css에 background 관련 코드(background-repeat 등) 이 없어도 됨에도 불구하고, 실험 게시물과 css를 공유하고 있는 상황이라 이렇게 포함하고 있어..! (물론 UI에 영향을 주는 건 없긴 해)

2022-05-22 17:16 UTC, kanghyun98 commented on projects/sasil-web/src/components/organisms/post/Post/Post.tsx
> +export const MiniCard = ({
내 생각엔 의뢰 페이지랑 실험 페이지가 동일한 구조를 가져가니깐, 도메인 대신에 `posts`라는 폴더명은 어때?
요런 느낌으로 두 개를 분리해놓는거지!
- `@/organisms/main/MiniCard`
- `@/organisms/posts/MiniCard`

그리고 위에서도 말하긴했는데 컴포넌트 명이 `MiniCard`니깐 폴더명도 `MiniCard`로 가져가는 방식은 어때?
`Post`라는 이름도 나쁘진 않은데, `Post`는 하나의 게시물이라는 의미에 더 가까운 것 같아서 나는 `MiniCard`가 더 좋은 것 같다고 생각해!

2022-05-22 17:18 UTC, kanghyun98 commented on projects/sasil-web/src/components/organisms/post/Post/Post.style.tsx
> +// ? 이때문에 의뢰 게시물은 배경 이미지가 아예 안들어감에도 불구하고 css에는 background 관련 코드가 들어가있는 상황.. 리팩토링 필요
UI상에서 문제 없다면 나는 괜찮다고 생각해!

2022-05-23 08:42 UTC, aube-dev requested changes

2022-05-23 08:42 UTC, aube-dev commented on projects/sasil-web/src/components/atoms/Like/Like.tsx
> + * 해당 게시물이 받은 누적 좋아요 수를 나타내는 컴포넌트
🍌 '좋아요'(혹은 '게시물')이라는 문맥이 있고, 아이콘이랑 텍스트 2개가 합쳐져 있는 구조다 보니 atom보단 molecule로 다루는 게 좋지 않을까 싶은데, 혹시 이 부분은 어떻게 생각해?

2022-05-23 08:42 UTC, aube-dev commented on projects/sasil-web/src/components/molelcules/WriterInfo/WriterInfo.tsx
> + */
이 부분은 그래서 `@param`으로 적지 말고, 위의 interface `WriterInfoProps`에다가 직접 적어주는 게 좋을 것 같아!
```typescript
export interface WriterInfoProps {
  /** 작성자 정보 객체 */
  writerObj: any;
```

2022-05-23 08:42 UTC, aube-dev commented on projects/sasil-web/src/components/molelcules/WriterInfo/WriterInfo.tsx
> + * @param textSize 닉네임 텍스트 크기
🍎  이런 prop은 위의 `WriterInfoProps`에는 없는 것 같은데 혼동을 막기 위해서 정확히 써주는 게 좋을 것 같아!

2022-05-23 08:42 UTC, aube-dev commented on projects/sasil-web/src/components/molelcules/WriterInfo/WriterInfo.tsx
> +  writerObj: any;
여기가 `any`인 이유는 아직 서버 부분을 안 만들어서 어떤 형태로 들어올지 모르기 때문인 건지 궁금합니다!
🍌 혹시 그런 거라면 TODO 주석으로 이 부분을 나중에 작업해야 함을 명시하는 게 좋을 것 같아!

2022-05-23 08:42 UTC, aube-dev commented on projects/sasil-web/src/components/organisms/post/Post/Post.tsx
> +export const MiniCard = ({
1. 속성이 다른 것일 뿐 하나의 `Post` 컴포넌트로 취급해야 하는 게 맞다고 생각! 그래서 얘네 둘을 분리하는 건 의미가 없는 것 같아.
2. `MiniCard`는 같은 디자인으로 main 말고도 다른 화면에서 쓰이고 있으니 main 도메인을 부여하는 건 적절하지 않은 것 같고, 게시물에 관한 것이니 post라는 도메인을 붙이는 게 어떨까? 같은 논리로 `WriterInfo`도 post 도메인에 포함될 수 있을 것 같고! (물론 post라는 도메인이 너무 비대해질 수도 있을 것 같은데, 이건 계속 해보면서 조절해야... 할듯?)
3. 나는 애초에 `Post`가 '하나의 게시물'을 나타내는 컴포넌트가 맞다고 생각했는데, 만약 detail 뷰와의 구분을 이야기하는 거라면 그건 어차피 하나의 organism 정도가 아니라 template 또는 page 단위로 갈 거기 때문에 구분이 가능할 것 같고, 이름은 `PostDetail` 등으로 지으면 되지 않을까 싶었어!
4. 나는 오히려 `MiniCard`라는 네이밍이 애매하게 느껴졌는데, 이유는 도메인이 있는 컴포넌트임에도 불구하고 도메인이 이름에서 전혀 드러나지 않아서 헷갈리더라구...

등등의 의견이 있는데, 이 부분은 회의에서 한번 같이 얘기해보면 좋을 것 같아!

2022-05-23 08:42 UTC, aube-dev commented on projects/sasil-web/src/components/organisms/post/Post/Post.tsx
> +        {title.length > 28 ? `${title.substring(0, 28)}...` : title}
🐰  오 이 방법은 생각을 못했네...
🥝 css에서 `text-overflow: ellipsis` 방식을 쓰는 것도 고려해보면 어떨까?

2022-05-24 06:07 UTC, ballsona commented on projects/sasil-web/src/components/molelcules/WriterInfo/WriterInfo.tsx
> + */
아 어떻게 처리해야하나 알아보고 있었는데, 그런 방법이 있군아.. 그럼 props 주석 처리는 광서가 말한대로 바꿀게요.!  땡큐 :)

2022-05-24 06:13 UTC, ballsona commented on projects/sasil-web/src/components/atoms/Like/Like.tsx
> + * 해당 게시물이 받은 누적 좋아요 수를 나타내는 컴포넌트
아 나는 어짜피 하트 아이콘은 style로? 고정이라 생각하면 `label` 이랑 비슷한거 아닌가 싶어서 atom이라 판단했는데, 듣고보니 '좋아요'를 표현한다는  의미있는 기능을 한다는 거 자체가  molecule로 봐야겠구나 ㅎㅎ.. 
그리고 `Like`에서 `StyledText` 를 쓰고 있는데 이게 또 atom이 atom을 사용하고 있는 셈이라 규칙 위반이네!? Molecule로 수정할게요 하하

2022-05-24 06:14 UTC, ballsona commented on projects/sasil-web/src/components/organisms/post/Post/Post.tsx
> +        {title.length > 28 ? `${title.substring(0, 28)}...` : title}
오 css로 처리가 가능한 부분이구나.. 역시 아는게 힘이다...

2022-05-25 05:22 UTC, merged