Work/68/73 comment delete UI
gdsc-ssu/sasil-front pull request #80
Opened 2022-07-25 09:23 UTC by ballsona

## Issue
#73 
## Description
- 댓글을 신고하고 삭제할 수 있는 dropdown 메뉴 컴포넌트 UI를 구현
- dropdown menu는 재사용 가능 

## Check List

- [X] PR 제목을 commit 규칙에 맞게 작성
- [X] WIP를 붙여야 하는 상황인지 확인
- [X] label 설정
- [X] 작업한 사람 모두를 Assign
- [X] Code Review 요청

2022-07-25 10:18 UTC, kanghyun98 reviewed
🐰 코로나 PR 이것 참 귀하군요.. 몸도 성치 않은데 너무너무 고생했슴다!!

2022-07-25 10:18 UTC, kanghyun98 commented on projects/sasil-web/src/components/templates/CommentsArea/CommentsAreaWrapped.tsx
> +    });
🥝 크게 중요한 부분은 아니지만, state 불변성 지키고, `useCallback`까지 해주면 더 좋을 것 같아요!

2022-07-25 10:18 UTC, kanghyun98 commented on projects/sasil-web/src/components/templates/CommentsArea/CommentsAreaWrapped.tsx
> +  };
🥝 `top`과 `left`의 default값을 0으로 주면, 하위 `setMenuDisplayInfo()`이 더 간결해질 수 있을 것 같아여!

2022-07-25 10:18 UTC, kanghyun98 commented on projects/sasil-web/src/components/templates/CommentsArea/CommentsAreaWrapped.tsx
> +  const onMenuDisplayChange = (top?: number, left?: number) => {
🥝 Change 대신 Toggle은 어떤가요?

2022-07-25 10:18 UTC, kanghyun98 commented on projects/sasil-web/src/components/templates/CommentsArea/CommentsArea.tsx
> +  onReportComment?: () => void;
🐰 주석이 아주 친절하네야

2022-07-25 10:18 UTC, kanghyun98 commented on projects/sasil-web/src/components/templates/CommentsArea/CommentsArea.style.tsx
> +});
🍌 여기랑 ... 아이콘에 `cursor: pointer` 넣어주세여!ㅋㅋ

2022-07-25 10:18 UTC, kanghyun98 commented on projects/sasil-web/src/components/molelcules/DropdownMenu/DropdownMenu.tsx
> +        <styles.FixedBackground onClick={() => onMenuDisplayChange?.()} />
optional chaining이 이렇게도 쓰일 수 있구나..! 하나 배워갑니다:)
그런데 `onMenuDisplayChange` 함수가 `undefined`가 될 수 있는 상황을 만들어놓은 이유는 재사용성 때문인가여?

2022-07-26 08:56 UTC, aube-dev commented on projects/sasil-web/src/components/templates/CommentsArea/CommentsAreaWrapped.tsx
> +    });
```suggestion
  const onMenuDisplayChange = useCallback((top?: number, left?: number) => {
    setMenuDisplayInfo(prev => ({
      display: !prev.display,
      top: top ?? 0,
      left: left ?? 0,
    }));
  }, []);

  const onDeleteComment = useCallback(() => {
    // TODO 댓글 삭제
    console.log('삭제');
    setMenuDisplayInfo(prev => ({
      ...prev,
      display: !prev.display,
    }));
  }, []);

  const onReportComment = useCallback(() => {
    // TODO 댓글 신고
    console.log('신고');
    setMenuDisplayInfo(prev => ({
      ...prev,
      display: !prev.display,
    }));
```

2022-07-26 08:57 UTC, aube-dev commented on projects/sasil-web/src/components/molelcules/DropdownMenu/DropdownMenu.tsx
> +        <styles.FixedBackground onClick={() => onMenuDisplayChange?.()} />
🥝 제 생각이 맞다면 이렇게도 쓸 수 있을 것 같아요!
```suggestion
        <styles.FixedBackground onClick={onMenuDisplayChange} />
```

2022-07-28 01:18 UTC, ballsona commented on projects/sasil-web/src/components/templates/CommentsArea/CommentsAreaWrapped.tsx
> +    });
오 손수 코드까지 제안해줘서 고마워요,, 둘다,, 수정해서 푸쉬하겠슴다!

2022-07-28 02:08 UTC, ballsona commented on projects/sasil-web/src/components/molelcules/DropdownMenu/DropdownMenu.tsx
> +        <styles.FixedBackground onClick={() => onMenuDisplayChange?.()} />
@aube-dev 아 내가 그렇게 못했던 이유를 보니까, 
`onMenuDisplayChange` 가 타입이 `(top?:number,left?number)=> void` 이라,  top,left를 인자로 전달해주면 dropdown menu 위치가 전달한 값으로 변경되고, 인자를 전달하지 않으면 그냥 위치를 0으로 설정해주는 함수라 저렇게 하면 에러가 떴었던 것 같아여! 
(말하다보니 너무 복잡하게 짠 것 같기도..)
![image](https://user-images.githubusercontent.com/67703882/181404766-02ab6a28-eb83-48ec-bf99-1dd856d54d7a.png)

2022-07-28 02:16 UTC, ballsona commented on projects/sasil-web/src/components/molelcules/DropdownMenu/DropdownMenu.tsx
> +        <styles.FixedBackground onClick={() => onMenuDisplayChange?.()} />
@kanghyun98 뭔가 추후에 드롭다운 메뉴 관련한 컴포넌트에 `onMenuDisplayChange` 함수가 없어도 될 상황?이 올 수도 있다 생각하여.. 일단 ?를 붙였던 것 같습니다,,!

2022-07-28 04:03 UTC, aube-dev commented on projects/sasil-web/src/components/molelcules/DropdownMenu/DropdownMenu.tsx
> +        <styles.FixedBackground onClick={() => onMenuDisplayChange?.()} />
아하 그런 상황이면 저게 맞긴 하겠다! 굿굿

2022-08-23 01:57 UTC, kanghyun98 requested changes
고생했슴다~~👍🏼👍🏼
사과 하나 있으니, 확인 부탁해여:)

2022-08-23 01:57 UTC, kanghyun98 commented on projects/sasil-web/src/components/templates/CommentsArea/CommentsArea.tsx
> +            />
저번에 얘기했을때는 수정기능은 안넣는다고 했던 것 같긴한데.. 한번 얘기해봅시다!

2022-08-23 01:57 UTC, kanghyun98 commented on projects/sasil-web/src/components/organisms/PostContent/PostContent.tsx
>        <Viewer ref={viewerRef} initialValue={post.content} />
🍎 정확하진 않지만 `PostContent`쪽에서 `ref` 관련 오류가 뜬 것 같은데, 확인 한번 부탁해여!

게시물 들어가면 아래 오류 확인 가능
![image](https://user-images.githubusercontent.com/70627979/186051483-2f62a58e-74c6-40d8-b39a-9e47978641cf.png)

2022-08-23 06:21 UTC, aube-dev commented on projects/sasil-web/src/components/organisms/PostContent/PostContent.tsx
>        <Viewer ref={viewerRef} initialValue={post.content} />
`MenuCircle`이 `forwardRef`로 정의된 컴포넌트가 아니라서 `ref` prop을 쓸 수 없는 것 같아요!

2022-08-24 12:38 UTC, ballsona commented on projects/sasil-web/src/components/organisms/Comment/Comment.style.tsx
> +});
아 hover하면 메뉴가 열리는 너낌...?

2022-08-24 12:38 UTC, ballsona commented on projects/sasil-web/src/components/molelcules/DropdownMenu/DropdownMenuItem.tsx
> +export default DropdownMenu;
아 이걸 확인못했네.. 감사합니다 ㅜㅜ

2022-08-24 12:45 UTC, ballsona commented on projects/sasil-web/src/components/molelcules/DropdownMenu/DropdownMenu.tsx
> +);
아아 원래는 오빠가 말해준대로 아이템 관련 객체를 전달하면 DropdownMenu 내부에서 map함수로 뿌려주는 방식으로 구현했었는데, 리팩토링하다가 보니까 DropdownMenu를 좀더 재사용성 있게 만들어보고 싶어서 더 복잡하긴 하지만 바꿔보았습니다,, (하지만 만들고 나니 DropdownMenu를 과연 다른 방식으로 쓸까 싶어서 후회중이기도 한.. ㅋㅋ)

2022-08-24 12:46 UTC, ballsona commented on projects/sasil-web/src/components/organisms/PostContent/PostContent.tsx
>        <Viewer ref={viewerRef} initialValue={post.content} />
아 svg 파일에 ref를 줘버려서 오류가 났었군아... 해결했습니다 !!

2022-08-28 09:46 UTC, merged