feat: add user-page components in web
gdsc-ssu/sasil-front pull request #85
Opened 2022-09-17 17:27 UTC by kanghyun98

## Issue
#78 #79

## Description
컴포넌트 추가 작업과 api 추가 작업을 합쳐버렸습니다! (api 추가하는게 너무 양이 적어서ㅎ)
- user-page 작업
- 실험/의뢰 페이지에서 api 호출 문제 해결 (기존에 2번씩 호출됐었음)

## Check List
- [x] PR 제목을 commit 규칙에 맞게 작성
- [x] WIP를 붙여야 하는 상황인지 확인
- [x] label 설정
- [x] 작업한 사람 모두를 Assign
- [x] Code Review 요청

2022-09-18 09:51 UTC, aube-dev requested changes
굿굿 너무 수고하셨슴다!!

2022-09-18 09:51 UTC, aube-dev commented on projects/sasil-web/src/logics/hooks/useInfiniteScroll.tsx
> +  callbackFunc: callbackFuncType | undefined,
🥝 요렇게 하면 어떨까요?
```suggestion
  callbackFunc?: callbackFuncType,
```

2022-09-18 09:51 UTC, aube-dev commented on projects/sasil-web/src/logics/hooks/useInfiniteScroll.tsx
>            curObserver.disconnect(); // 관측 해제
🍌 혹시 이 분기 처리의 의도가 어떻게 되나요? 이 상황에서는 `callbackFunc`이 있어야만 아래의 `curObserver.disconnect()`도 실행이 되는 것 같은데, 만약 이게 의도가 아니고 단순히 `callbackFunc`을 실행해야 될지 말지를 결정하는 거라면 다음과 같이 고치는 게 나을 것 같아요!

```suggestion
        if (entries[0].isIntersecting) {
          callbackFunc?.(); // 여기서 전역 상태를 업데이트 해야함

          curObserver.disconnect(); // 관측 해제
```

2022-09-18 09:51 UTC, aube-dev commented on projects/sasil-web/src/pages/experiment.tsx
> +    .map((res) => (res && res.isSuccess ? res.result.list : []))
🥝 이렇게 하면 어떨까요?
```suggestion
    .map((res) => (res?.isSuccess ? res.result.list : []))
```

2022-09-18 09:51 UTC, aube-dev commented on projects/sasil-web/src/pages/request.tsx
> +    .map((res) => (res && res.isSuccess ? res.result.list : []))
🥝 위와 같은 코멘트입니다!

2022-09-19 10:09 UTC, kanghyun98 commented on projects/sasil-web/src/logics/hooks/useInfiniteScroll.tsx
> +  callbackFunc: callbackFuncType | undefined,
생각해보니 다른 컴포넌트에서도 그 방식을 사용한 것 같다! 반영할게여~

2022-09-19 10:09 UTC, kanghyun98 commented on projects/sasil-web/src/logics/hooks/useInfiniteScroll.tsx
>            curObserver.disconnect(); // 관측 해제
작성해준 방법으로 적용해보고 로직 상 문제 없으면 반영할게여!

2022-09-19 10:09 UTC, kanghyun98 commented on projects/sasil-web/src/pages/experiment.tsx
> +    .map((res) => (res && res.isSuccess ? res.result.list : []))
optional chaining이 더 깔끔하네여!

2022-09-19 12:33 UTC, kanghyun98 commented on projects/sasil-web/src/logics/hooks/useInfiniteScroll.tsx
>            curObserver.disconnect(); // 관측 해제
disconnect가 callbackFunc 존재 여부에 상관없이 반영되는게 맞는데, 로직을 잘못 변경했었네여.. 반영 했습니다!

2022-09-21 04:19 UTC, ballsona approved these changes
굳굳 수고하셨슴당 ~~ 👍

2022-09-21 04:19 UTC, ballsona commented on projects/sasil-web/src/pages/user/[uid].tsx
> +const UserPage: NextPage = () => {
네비게이션바에서 유저 아이콘 누르면 아직 `/user`로 이동해서 마이페이지가 안뜨는데, 요거는 나중에 합칠때 수정할 계획이신거져,,?

2022-09-21 04:19 UTC, ballsona commented on projects/sasil-web/src/components/molelcules/SwitchButton/SwitchButton.tsx
> +const SwitchButton = ({
오 storybook으로 보니까 버튼 깔삼해요 ... 자꾸 토글하고 싶게 만드셨어요 👍

2022-09-21 04:26 UTC, kanghyun98 commented on projects/sasil-web/src/pages/user/[uid].tsx
> +const UserPage: NextPage = () => {
넵,, 마자여.. 개인적으로 생각해본 방식은 jotai를 이용해 유지하고 있는 유저 전역상태 값을 이용해서 마이페이지로 이동할 수 있게 만들까 생각중입니돠..

2022-09-22 14:24 UTC, merged